#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.
# 
# Modified by Johann Moller <johannm@gmail.com>

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $plug;
my $batt0;
my $batt1;
my $batt2;
my $batt3;
my $batt4;

my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;
#$full_text = "$percent%";

#Font Awesome Glyphs
$plug  = ''; #fa-plug
$batt0 = ''; #fa-battery-0
$batt1 = ''; #fa-battery-1
$batt2 = ''; #fa-battery-2
$batt3 = ''; #fa-battery-3
$batt4 = ''; #fa-battery-4

if ($status eq 'Charging') {
	$full_text .= $plug;
} elsif ($status eq 'Discharging') {
        if ($percent < 15) {
	    $full_text .= $batt0;
	} elsif ($percent < 30) {
	    $full_text .= $batt1;
	} elsif ($percent < 55) {
	    $full_text .= $batt2;
	} elsif ($percent < 80) {
	    $full_text .= $batt3;
	} else {
	    $full_text .= $batt4;
        }    
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
	$full_text .= " ($1)";
}

# print text
print "$full_text\n";
print "$short_text\n";

# consider color and urgent flag only on discharge
if ($status eq 'Discharging') {

	if ($percent < 20) {
		print "#FF0000\n";
	} elsif ($percent < 40) {
		print "#FFAE00\n";
	} elsif ($percent < 60) {
		print "#FFF600\n";
	} elsif ($percent < 85) {
		print "#A8FF00\n";
	}

	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
